=== NotEnoughUpdates/NotEnoughUpdates/gradle/MoulConfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?><xs:schema xmlns="http://notenoughupdates.org/moulconfig" elementFormDefault="qualified" targetNamespace="http://notenoughupdates.org/moulconfig" xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:complexType name="Widgetless"/><xs:complexType name="SingleWidget"><xs:group ref="AnyWidget"/></xs:complexType><xs:complexType name="MultiWidget"><xs:group maxOccurs="unbounded" minOccurs="0" ref="AnyWidget"/></xs:complexType><xs:group name="AnyWidget"><xs:choice><xs:element name="Text" type="Text"/><xs:element name="Scale" type="Scale"/><xs:element name="Center" type="Center"/><xs:element name="Slider" type="Slider"/><xs:element name="Row" type="Row"/><xs:element name="Gui" type="Gui"/><xs:element name="TextField" type="TextField"/><xs:element name="ScrollPanel" type="ScrollPanel"/><xs:element name="ItemStack" type="ItemStack"/><xs:element name="Array" type="Array"/><xs:element name="Hover" type="Hover"/><xs:element name="Spacer" type="Spacer"/><xs:element name="Column" type="Column"/><xs:element name="Button" type="Button"/><xs:element name="Switch" type="Switch"/></xs:choice></xs:group><xs:element name="Root" type="Root"/><xs:complexType name="Text"><xs:complexContent><xs:extension base="Widgetless"><xs:attribute name="split"/><xs:attribute name="shadow"/><xs:attribute name="textAlign"/><xs:attribute name="width"/><xs:attribute name="text" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Scale"><xs:complexContent><xs:extension base="SingleWidget"><xs:attribute name="scale" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Center"><xs:complexContent><xs:extension base="SingleWidget"/></xs:complexContent></xs:complexType><xs:complexType name="Root"><xs:complexContent><xs:extension base="SingleWidget"/></xs:complexContent></xs:complexType><xs:complexType name="Slider"><xs:complexContent><xs:extension base="Widgetless"><xs:attribute name="minValue" use="required"/><xs:attribute name="maxValue" use="required"/><xs:attribute name="minStep"/><xs:attribute name="width"/><xs:attribute name="value" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Row"><xs:complexContent><xs:extension base="MultiWidget"/></xs:complexContent></xs:complexType><xs:complexType name="Gui"><xs:complexContent><xs:extension base="SingleWidget"/></xs:complexContent></xs:complexType><xs:complexType name="TextField"><xs:complexContent><xs:extension base="Widgetless"><xs:attribute name="value" use="required"/><xs:attribute name="width"/><xs:attribute name="editable"/><xs:attribute name="suggestion"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="ScrollPanel"><xs:complexContent><xs:extension base="SingleWidget"><xs:attribute name="width" use="required"/><xs:attribute name="height" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="ItemStack"><xs:complexContent><xs:extension base="Widgetless"><xs:attribute name="value" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Array"><xs:complexContent><xs:extension base="SingleWidget"><xs:attribute name="data" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Hover"><xs:complexContent><xs:extension base="SingleWidget"><xs:attribute name="lines" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Spacer"><xs:complexContent><xs:extension base="Widgetless"><xs:attribute name="width"/><xs:attribute name="height"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Column"><xs:complexContent><xs:extension base="MultiWidget"/></xs:complexContent></xs:complexType><xs:complexType name="Button"><xs:complexContent><xs:extension base="SingleWidget"><xs:attribute name="margin"/><xs:attribute name="onClick" use="required"/></xs:extension></xs:complexContent></xs:complexType><xs:complexType name="Switch"><xs:complexContent><xs:extension base="Widgetless"><xs:attribute name="animationSpeed"/><xs:attribute name="value" use="required"/></xs:extension></xs:complexContent></xs:complexType></xs:schema>

=== NotEnoughUpdates/NotEnoughUpdates/src/main/resources/assets/notenoughupdates/gui/customtodos/edit.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (C) 2023 NotEnoughUpdates contributors
  ~
  ~ This file is part of NotEnoughUpdates.
  ~
  ~ NotEnoughUpdates is free software: you can redistribute it
  ~ and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation, either
  ~ version 3 of the License, or (at your option) any later version.
  ~
  ~ NotEnoughUpdates is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public License
  ~ along with NotEnoughUpdates. If not, see <https://www.gnu.org/licenses/>.
  -->

<Root xmlns="http://notenoughupdates.org/moulconfig"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://notenoughupdates.org/moulconfig https://raw.githubusercontent.com/NotEnoughUpdates/MoulConfig/master/MoulConfig.xsd">
    <Gui>
        <Column>
            <Meta afterClose="@afterClose"/>
            <Row>
                <Button onClick="@close">
                    <Text text="←"/>
                </Button>
                <Text text="@getTitle"/>
            </Row>
            <Row>
                <Text text="Enabled: " width="150"/>
                <Switch value="@enabled"/>
            </Row>
            <Row>
                <Text text="Label: " width="150"/>
                <TextField width="300" value="@label" suggestion="Label"/>
            </Row>
            <Row>
                <Text text="Icon: " width="132"/>
                <ItemStack value="@getItemStack"/>
                <TextField width="300" value="@icon" suggestion="Item ID"/>
            </Row>
            <Row>
                <Text text="Reset after (seconds): " width="150"/>
                <TextField width="300" value="@timer"/>
            </Row>
            <Row>
                <Text text="Reset at fixed time: " width="150"/>
                <Switch value="@isResetOffset"/>
            </Row>
            <Row>
                <Text text="@getFancyTimeTimer" width="300"/>
            </Row>
            <Row>
                <Button onClick="@minusDayTimer">
                    <Text text="-Day"/>
                </Button>
                <Button onClick="@minusHourTimer">
                    <Text text="-Hour"/>
                </Button>
                <Button onClick="@minusMinuteTimer">
                    <Text text="-Minute"/>
                </Button>
                <Button onClick="@plusMinuteTimer">
                    <Text text="+Minute"/>
                </Button>
                <Button onClick="@plusHourTimer">
                    <Text text="+Hour"/>
                </Button>
                <Button onClick="@plusDayTimer">
                    <Text text="+Day"/>
                </Button>
            </Row>
            <Row>
                <Text text="Show only when (seconds): " width="150"/>
                <TextField width="300" value="@showWhen"/>
            </Row>
            <Row>
                <Text text="Show only when ready: " width="150"/>
                <Switch value="@showOnlyWhenReady"/>
            </Row>
            <Row>
                <Text text="@getFancyTimeShowWhen" width="300"/>
            </Row>
            <Row>
                <Button onClick="@minusDayShowWhen">
                    <Text text="-Day"/>
                </Button>
                <Button onClick="@minusHourShowWhen">
                    <Text text="-Hour"/>
                </Button>
                <Button onClick="@minusMinuteShowWhen">
                    <Text text="-Minute"/>
                </Button>
                <Button onClick="@plusMinuteShowWhen">
                    <Text text="+Minute"/>
                </Button>
                <Button onClick="@plusHourShowWhen">
                    <Text text="+Hour"/>
                </Button>
                <Button onClick="@plusDayShowWhen">
                    <Text text="+Day"/>
                </Button>
            </Row>
            <Row>
                <Text text="Trigger: " width="150"/>
                <TextField value="@trigger" width="300" suggestion="Trigger"/>
            </Row>
            <Row>
                <Button onClick="@setChat">
                    <Text text="@getChat"/>
                </Button>
                <Button onClick="@setActionbar">
                    <Text text="@getActionbar"/>
                </Button>

                <Button onClick="@setSidebar">
                    <Text text="@getSidebar"/>
                </Button>

                <Button onClick="@setTablist">
                    <Text text="@getTablist"/>
                </Button>
            </Row>
            <Row>
                <Button onClick="@setRegex">
                    <Text text="@getRegex"/>
                </Button>
                <Button onClick="@setStartsWith">
                    <Text text="@getStartsWith"/>
                </Button>
                <Button onClick="@setContains">
                    <Text text="@getContains"/>
                </Button>
                <Button onClick="@setEquals">
                    <Text text="@getEquals"/>
                </Button>
            </Row>
            <Row>
                <Button onClick="@copyTemplate">
                    <Text text="Copy Preset"/>
                </Button>
                <Button onClick="@markAsReady">
                    <Text text="Mark as Ready"/>
                </Button>
                <Button onClick="@markAsCompleted">
                    <Text text="Mark as Done"/>
                </Button>
            </Row>
        </Column>
    </Gui>
</Root>
